[package]
name = "ranim-014"
version = "0.1.0"
edition = "2024"

[features]
preview = ["ranim/preview"]

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
ranim = { path = "../../../ranim" }
include-lines = "1.1.2"
