[package]
name = "vitem-visualize"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "dylib"]

[features]
app = ["ranim/app"]

[dependencies]
# ranim.workspace = true
ranim = { workspace = true, features = ["app"] }
itertools.workspace = true
